### ISSUE TITLE
I wonder how to split dataset

### ISSUE THREAD

**Issue by ghdwnsgh852** [JayRothenberger/Meta-Co-Training#1]
how did you split train, test, valid?

**Comment by JayRothenberger** [comment]
I am using the official train, validation, and testing dataset splits available in PyTorch and from the websites of the competitions that published them.  Some datasets have available test sets (such as FGVCAircraft, and Flowers102), while others do not (such as ImageNet, iNaturalist).  For the 1% and 10% training sets on ImageNet I use the official subsets published as part of the SimCLRv2 paper.  For the other datasets I randomly sample a percentage of the original training set and use cascade rounding to ensure the class frequencies are as close as possible to the frequencies in the original dataset.

This is the file where the sampling occurs:
https://github.com/JayRothenberger/Meta-Co-Training/blob/0460ef0b12ff81594cccedbccc2dd189d7a0ae32/utils.py#L292
