### ISSUE TITLE
Question for training and prediction

### ISSUE THREAD

**Issue by FEIPNG** [JayRothenberger/Meta-Co-Training#2]
Hello ! Thank you for your excellent job.  

Firstly, regarding training, in the README, there is a section titled "Example Usage: MCT_experiment.py". It mentions a file named "MCT_bench.py", but I cannot find it. Could you please clarify its purpose?

As for prediction after training, I am new to this domain and would like to ask if you have a template or guidelines for conducting prediction the class of image?

Thank you very much!

**Comment by JayRothenberger** [comment]
Regarding the README:

Thank you for your comment.  I had made a typo in the readme, and it should have read "MCT_experiment.py"  I have just changed that.

Regarding loading saved models after training:

Each model checkpoint after training is saved to a unique path based on the combination of hyperparameters.  I think it should be clear (especially if you have trained only one model) what the name of that file is if you look in the directory set on this line:

https://github.com/JayRothenberger/Meta-Co-Training/blob/9dc8a992b0e279d1660382e2d4518a1e3d353bfc/MCT_experiment.py#L288

If it is not clear though, then there is a file in the directory specified by the "path" argument which is called "registry.pkl".  This file has the format specified here:

https://github.com/JayRothenberger/Meta-Co-Training/blob/9dc8a992b0e279d1660382e2d4518a1e3d353bfc/DAHS/DAHB.py#L86

It is just a simple dictionary, and all of the runs that have finished and saved checkpoints are accessible using the key "finished" in that dictionary.  The checkpoint paths are stored along with the best performance achieved and the combination of hyperparamers used for the run. 

Regarding inference after training:

You should just be able to load the model checkpoints into an architecture of the same type.  All of the models used are of the same form:

https://github.com/JayRothenberger/Meta-Co-Training/blob/9dc8a992b0e279d1660382e2d4518a1e3d353bfc/MCT_experiment.py#L118

so you should just be able to initialize a model like this and then load the saved state into it.  I will be releasing a new version of the code soon which makes this a little easier and which allows fine-tuning of the backbones as well as the MLP head.

**Comment by FEIPNG** [comment]
Thank you very much! It is clear to me. I will give it a try! I am also looking forward to your new code!

I finished a training with SwAV and DINOV2, and I tried to load a model with a new file eval.py for prediction. Here is the code for loading the model : 

model_path = '/mnt/d/Meta-Co-Training/Grid_MCT_IN1K/checkpoints/D_V_0.01_True_0.pt'
state_dict = torch.load(model_path)

model = FCNN(test_dataset[0][0].shape[-1], num_classes, [1024, 1024, 1024], nn.BatchNorm1d, nn.ReLU, dropout=0.2).to(0)

model.load_state_dict(state_dict)

But I got the message error : 
    state_dict = torch.load(model_path)
  File "..../anaconda3/envs/mct/lib/python3.9/site-packages/torch/serialization.py", line 1040, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "..../anaconda3/envs/mct/lib/python3.9/site-packages/torch/serialization.py", line 1260, in _legacy_load
    raise RuntimeError("Invalid magic number; corrupt file?")
RuntimeError: Invalid magic number; corrupt file?

Is it normal to have this error ? Perhaps I need to retrain my model ?

**Comment by JayRothenberger** [comment]
Can you try loading with pickle instead?  It looks like the DistributedAsynchronousGridSearch object saves the state with pickle instead of torch.  I should probably change one of the two hyperparameter search objects so that they are consistent.

**Comment by FEIPNG** [comment]
Thank you very much! It works! It was my fault, because I didn't use pickle before, I am not familiar with it.
