### ISSUE TITLE
How to train a custom dataset for 6 classes

### ISSUE THREAD

**Issue by uusei** [JayRothenberger/Meta-Co-Training#3]

**Comment by uusei** [comment]
I want to train a dataset for pictures for  6 classes with 10% labeled,what should I do to change the code for the custom dataset

**Comment by JayRothenberger** [comment]
I believe the easiest way to modify the current example is to write your own `make_dataset` function like here:

https://github.com/JayRothenberger/Meta-Co-Training/blob/9dc8a992b0e279d1660382e2d4518a1e3d353bfc/MCT_experiment.py#L115

Then create a model that takes instances from that dataset as input and has the desired `num_classes` as output and replace the lines here:

https://github.com/JayRothenberger/Meta-Co-Training/blob/9dc8a992b0e279d1660382e2d4518a1e3d353bfc/MCT_experiment.py#L118

Let me know if you run into any further issues.  Thank you for your interest in the project, and I apologize that it took me so long to respond.  I am working on a more friendly and better-written version of the repository that I hope to release soon.

Jay

**Comment by uusei** [comment]
Thank you very much! Actually,I also change the file `embed_dataset.py` and create a new dataset loader to read custom  images and labels.And it works!
